-- Your SQL goes here
CREATE TABLE files (
    id INTEGER NOT NULL PRIMARY KEY,
    file_name TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    profile_id INTEGER NOT NULL,
    FOREIGN KEY(profile_id) REFERENCES profiles(id)
);